export const conf = {
  API_BASE_URL: process.env.NEXT_PUBLIC_BACKEND_API_BASE_URL,
  HOTJAR_ID: process.env.NEXT_PUBLIC_HOTJAR_ID,
  AMPLITUDEANALYTICS_TOKEN: process.env.NEXT_PUBLIC_AMPLITUDEANALYTICS_TOKEN,
  PROPERTY_ID: process.env.NEXT_PUBLIC_TAWK_PROPERTY_ID,
  WEIGHT_ID: process.env.NEXT_PUBLIC_TAWK_WEIGHT_ID,
};
